### ISSUE TITLE
ulid package missing from tweets go example

### ISSUE THREAD

**Issue by charlesonunze** [rotationalio/ensign-examples#10]
The ulid package is missing from the ensign tweets example for go, which causes the application to crash.

**Comment by rebeccabilbro** [comment]
Thank you @charlesonunze for flagging this! We'll be sure to update that example in our next release, but feel free to open a PR before then to fix the bug if you wish!

**Comment by charlesonunze** [comment]
Hi @rebeccabilbro, I’ve pushed a PR that should fix this
